# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-5683-ubuntuFPGA/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_vhdl -lib xpm /home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib neorv32 {
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_package.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_bootrom.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_bootrom_image.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_bootrom_rom.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_bus.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_prim.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cache.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cache_ram.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cfs.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_clint.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_decompressor.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_frontend.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_control.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_hwtrig.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_counters.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_regfile.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_alu_shifter.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_alu_muldiv.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_alu_bitmanip.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_alu_fpu.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_alu_cfu.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_alu_cond.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_alu_crypto.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_alu.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_lsu.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_pmp.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu_trace.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_cpu.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_debug_auth.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_debug_dm.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_debug_dtm.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_dma.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_dmem.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_dmem_ram.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_gpio.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_gptmr.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_imem.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_imem_image.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_imem_ram.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_imem_rom.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_neoled.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_onewire.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_pwm.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_sdi.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_slink.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_spi.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_sys.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_sysinfo.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_xbus.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_wdt.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_uart.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_twi.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_twd.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_trng.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_tracer.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32/neorv32_top.vhd
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/xbus2axi4_bridge.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ipshared/5917/src/neorv32_vivado_ip.vhd
      /home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ip/design_1_neorv32_vivado_ip_0_0/synth/design_1_neorv32_vivado_ip_0_0.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_neorv32_vivado_ip_0_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-5683-ubuntuFPGA/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
