set_property SRC_FILE_INFO {cfile:/home/bkanaley/lab_3_jun_7/lab_3_jun_7.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc rfile:../../../../../lab_3_jun_7.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/lab_3_jun_7/lab_3_jun_7.runs/design_1_axi_smc_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:3 order:LATE scoped_inst:inst/m00_exit_pipeline/m00_exit/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:4 order:LATE scoped_inst:inst/s00_entry_pipeline/s00_mmu/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:5 order:LATE scoped_inst:inst/s00_entry_pipeline/s00_si_converter/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:6 order:LATE scoped_inst:inst/s00_entry_pipeline/s00_transaction_regulator/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:7 order:LATE scoped_inst:inst/s00_nodes/s00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:8 order:LATE scoped_inst:inst/s00_nodes/s00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:9 order:LATE scoped_inst:inst/s00_nodes/s00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:10 order:LATE scoped_inst:inst/s00_nodes/s00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:11 order:LATE scoped_inst:inst/s00_nodes/s00_b_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:12 order:LATE scoped_inst:inst/s00_nodes/s00_b_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:13 order:LATE scoped_inst:inst/s00_nodes/s00_r_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:14 order:LATE scoped_inst:inst/s00_nodes/s00_r_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:15 order:LATE scoped_inst:inst/s00_nodes/s00_w_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:16 order:LATE scoped_inst:inst/s00_nodes/s00_w_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_single.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_single.tcl id:17 order:LATE scoped_inst:inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bkanaley/Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_single.tcl rfile:../../../../../../Vivado/2025.1/Vivado/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_single.tcl id:18 order:LATE scoped_inst:inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT unmanaged:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 10.000 -name aclk [get_ports aclk]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_exit_pipeline/m00_exit/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_entry_pipeline/s00_mmu/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_entry_pipeline/s00_si_converter/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_entry_pipeline/s00_transaction_regulator/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_b_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_b_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_r_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_r_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_w_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_w_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
current_instance inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX
set_property src_info {type:SCOPED_XDC file:17 line:5 export:INPUT save:NONE read:READ} [current_design]
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance
current_instance inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT
set_property src_info {type:SCOPED_XDC file:18 line:5 export:INPUT save:NONE read:READ} [current_design]
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_b_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_r_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_w_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_b_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_r_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_nodes/s00_w_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/m00_exit_pipeline/m00_exit/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_entry_pipeline/s00_mmu/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_entry_pipeline/s00_si_converter/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/s00_entry_pipeline/s00_transaction_regulator/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT]
